UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferior',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2';UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferioroiopioipoipo',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2';UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferior',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferioroiopioipoipo',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferior',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferioroiopioipoipo',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferior dsadasdsadsadasdsa',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '8';UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferior',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferioroiopioipoipo',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no SeminÃ¡rio Instabilidade DinÃ¢mica no Membro Inferior',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas JoÃ£o Rocha Vaz e RaÃºl Oliveira estiveram presentes no SeminÃ¡rio Instabilidade DinÃ¢mica no Membro Inferior, organizado pelo LaboratÃ³rio de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas JoÃ£o Rocha Vaz e RaÃºl Oliveira estiveram presentes no SeminÃ¡rio Instabilidade DinÃ¢mica no Membro Inferior, organizado pelo LaboratÃ³rio de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no SeminÃ¡rio Instabilidade DinÃ¢mica no Membro Inferioroiopioipoipo',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas JoÃ£o Rocha Vaz e RaÃºl Oliveira estiveram presentes no SeminÃ¡rio Instabilidade DinÃ¢mica no Membro Inferior, organizado pelo LaboratÃ³rio de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas JoÃ£o Rocha Vaz e RaÃºl Oliveira estiveram presentes no SeminÃ¡rio Instabilidade DinÃ¢mica no Membro Inferior, organizado pelo LaboratÃ³rio de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferior',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'UPDATE requilib_website.destaque 
				  SET titulo = 'Fisioterapeutas da R\'equilibrius participaram no Seminário Instabilidade Dinâmica no Membro Inferioroiopioipoipo',
					  resumo = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.',
					  texto = 'No passado dia 12 de Novembro, os Fisioterapeutas João Rocha Vaz e Raúl Oliveira estiveram presentes no Seminário Instabilidade Dinâmica no Membro Inferior, organizado pelo Laboratório de Comportamento Motor da FMH.'
				WHERE id = '2'